routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
Route::get('/user/verify/{token}', 'Auth\RegisterController@verifyUser');
Route::match(['get', 'post'], 'ajax-image-upload-reg', 'Auth\RegisterController@uploadImage');
Route::delete('ajax-remove-image-reg/{filename}', 'Auth\RegisterController@deleteImage');
Route::group(array('before' => 'auth'), function(){
    Route::get('/', 'HomeController@index');
    Route::resource('user','UserController');
    Route::delete('role/{id}/delete','RoleController@deleterole')->name('roledelete');

    Route::resource('role','RoleController');
    Route::match(['get', 'post'], 'ajax-image-upload', 'UserController@uploadImage');
    Route::delete('ajax-remove-image/{filename}', 'UserController@deleteImage');
});

app/Role.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class Role extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'user_id','can_view','can_edit','can_add','can_delete',
    ];
    protected $table = "user_role";

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [];
    
    
    public function modulelist(){
        return $this->belongsTo("\App\Systemmodule","module_id");

    }
}

app/Http/Controllers/RoleController.php
<?php
namespace App\Http\Controllers;

use Illuminate\Support\Facades\Auth;
use App\User,App\Role,App\Systemmodule;
use Illuminate\Http\Request;
use DB;
use Validator;


class RoleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
         $this->middleware('auth');
    }

    public function index()
    {
        if(\Auth::user()->user_role==2){
            $user = User::select("users.*")
            ->rightJoin('user_role', 'users.id', '=', 'user_role.user_id')
            ->groupBy('users.id')
            ->get();
       
        }else{
            $user = User::where('id',\Auth::user()->id)->get();
        }
        return view('role.index',compact('user'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $assignuser = Role::select("user_role.user_id")->where('user_role.status','1')->groupBy('user_id')->pluck('user_id');
        $user = User::whereNotIn('users.id',[$assignuser])->where('id','!=',\Auth::user()->id)->get();
        $modules = Systemmodule::where('status','1')->get();
        return view('role.create',compact('user','modules'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $userId=$request->selectuser;
        $modules = Systemmodule::where('status','1')->get();
        foreach($modules as $modKey=>$modVal){
            $UserRole = new Role;
            $UserRole->user_id = $userId;
            $UserRole->can_view = (@$request->view[$modVal['id']]) ? '1' : '0';
            $UserRole->can_write = (@$request->add[$modVal['id']]) ? '1' : '0';
            $UserRole->can_edit = (@$request->edit[$modVal['id']]) ? '1' : '0';
            $UserRole->can_delete = (@$request->delete[$modVal['id']]) ? '1' : '0'; 
            $UserRole->module_id=$modVal['id'];
            $UserRole->save();
        }
        return redirect()->route('role.index')->with('success','User role has been created successfully.');

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        
        $user = User::where('id',$id)->get();
        $modules = Role::with(['modulelist'])->select("user_role.*")
        ->leftJoin('system_module', 'user_role.module_id', '=', 'system_module.id')
        ->where('user_role.status','1')
        ->where('user_role.user_id',$id)->get();
        return view('role.show',compact('user','modules'));
    
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
       
        $user = User::where('id',$id)->get();
       
        $modules = Role::with(['modulelist'])->select("user_role.*","system_module.id as sysmid","system_module.id as smuid")
        ->leftJoin('system_module', 'user_role.module_id', '=', 'system_module.id')
        ->where('user_role.status','1')
        ->where('user_role.user_id',$id)->get();
          return view('role.edit',compact('user','modules'));

    }
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        $userId=$request['selectuser'];
        $modules = Systemmodule::where('status','1')->get();
        foreach($modules as $modKey=>$modVal){
            $UserRole = Role::find($request->rowid[$modVal['id']]);
            $UserRole->user_id = $userId;
            $UserRole->can_view = (@$request->view[$modVal['id']]) ? '1' : '0';
            $UserRole->can_write = (@$request->add[$modVal['id']]) ? '1' : '0';
            $UserRole->can_edit = (@$request->edit[$modVal['id']]) ? '1' : '0';
            $UserRole->can_delete = (@$request->delete[$modVal['id']]) ? '1' : '0'; 
            $UserRole->module_id=$modVal['id'];
            $UserRole->save();
        }
            
        return redirect()->route('role.index')->with('success','User role has been updated successfully');
        
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function deleterole(Request $request,$id)
    {
        Role::where("user_id",$id)->delete();
        return redirect()->route('role.index')
        ->with('success','User role has been deleted successfully');
        
    }
    
}

resources/views/role/create.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <div class="row">
        <div class="col-md-12 col-md-offset-0">
            <div class="panel panel-default">
                <div class="panel-heading"> Add Role</div>

                <div class="panel-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                                    
                    @if ($errors->any())
                    <div class="alert alert-danger">
                        <strong>Whoops!</strong> There were some problems with your input.<br><br>
                        <ul>
                            @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                    @endif                                        
                    <div class="row">
                        <div class="col-lg-12 margin-tb">
                            <div class="pull-left">
                                
                            </div>
                            <div class="pull-right">
                                <a class="btn btn-primary" href="{{ route('role.index') }}"> Back</a>
                            </div>
                        </div>
					</div>
					
					<form action="{{ route('role.store') }}" id="signupForm" method="POST">
						<input type="hidden" name="_token" value="{{ csrf_token() }}">
						<div class="row">
							<div class="col-xs-12 col-sm-12 col-md-12">
								<div class="form-group">
									<strong>Select User:</strong>
									<select name="selectuser" class="form-control" id="selectuser">
										<?php 
										foreach($user as $selectuserKey=>$selectuserVal){
											?>
											<option value="<?=$selectuserVal['id']?>"><?=$selectuserVal['name'].' '.$selectuserVal['last_name']?></option>
											<?php
										}
										?>
									</select>
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-xs-12 col-sm-12 col-md-12">
								<div class="table-responsive">
									<table class="table">
										<thead>
											<tr>
											  <th scope="col">Module Name</th>
											  <th scope="col">Add</th>
											  <th scope="col">Edit</th>
											  <th scope="col">Delete</th>
											  <th scope="col">View</th>
											</tr>
										  </thead>
										  <tbody>
									
											 
								
									<?php 
											foreach($modules as $modulesKey=>$modulesVal){
										?>
										<tr>
											<td>
												<?php echo $modulesVal['module_name'];?>
											</td>	
										<td>
											<input type="checkbox" name="add[<?php echo $modulesVal['id'];?>]">
										</td>
										<td>
											<input type="checkbox" name="edit[<?php echo $modulesVal['id'];?>]">
										</td>
										<td>
											<input type="checkbox" name="delete[<?php echo $modulesVal['id'];?>]">
										</td>
										<td>
											<input type="checkbox" name="view[<?php echo $modulesVal['id'];?>]">
										<td>
						<?php 
											}
										?>
										</tbody>
									</table>
									</div>
								</div>	
							</div>	
						
							<div class="col-xs-12 col-sm-12 col-md-12 text-center">
								<button type="submit" class="btn btn-primary">Submit</button>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection
@section('page-js-script')
<script type="text/javascript">
    $(document).ready(function() {
	$("#signupForm").validate({
			rules: {
				firstname: "required",
				lastname: "required",
				name: {
					required: true,
					minlength: 2
				},
				password: {
					required: true,
					minlength: 5
				},
				password_confirmation: {
					required: true,
					minlength: 5,
					equalTo: "#password"
				},
				email: {
					required: true,
					email: true
				}
			},
			messages: {
				name: {
					required: "Please enter a username",
					minlength: "Your username must consist of at least 2 characters"
				},
				password: {
					required: "Please provide a password",
					minlength: "Your password must be at least 5 characters long"
				},
				password_confirmation: {
					required: "Please provide a confirm password",
					minlength: "Your password must be at least 5 characters long",
					equalTo: "Please enter the same password as above"
				},
				email: "Please enter a valid email address"
				
			}
		});
    });
</script>
<script>
    $(document).ready(function() {
    	 $("#loader").fadeOut("slow");
	});
</script>
@stop

resources/views/role/edit.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <div class="row">
        <div class="col-md-12 col-md-offset-0">
            <div class="panel panel-default">
                <div class="panel-heading"> Edit Role</div>

                <div class="panel-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                                    
                    @if ($errors->any())
                    <div class="alert alert-danger">
                        <strong>Whoops!</strong> There were some problems with your input.<br><br>
                        <ul>
                            @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                    @endif
                                        
                                        
                    <div class="row">
                        <div class="col-lg-12 margin-tb">
                            <div class="pull-left">
                                
                            </div>
                            <div class="pull-right">
                                <a class="btn btn-primary" href="{{ route('role.index') }}"> Back</a>
                            </div>
                        </div>
                    </div>
                   
                    <form action="{{ route('role.update',$user[0]['id']) }}" method="POST">
                        <input type="hidden" name="_method" value="PUT">
                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                        <div class="row">
							<div class="col-xs-12 col-sm-12 col-md-12">
								<div class="form-group">
									<strong>Selected User:</strong>
									<select name="selectuser" class="form-control" id="selectuser">
										<?php 
										foreach($user as $selectuserKey=>$selectuserVal){
											?>
											<option value="<?=$selectuserVal['id']?>"><?=$selectuserVal['name'].' '.$selectuserVal['last_name']?></option>
											<?php
										}
										?>
									</select>
								</div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <strong>Email:</strong>
                                    {{ $user[0]['email'] }}
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="table-responsive">
									<table class="table">
										<thead>
											<tr>
											  <th scope="col">Module Name</th>
											  <th scope="col">Add</th>
											  <th scope="col">Edit</th>
											  <th scope="col">Delete</th>
											  <th scope="col">View</th>
											</tr>
										  </thead>
										  <tbody>
                                                <?php 
                                                foreach($modules as $modulesKey=>$modulesVal){
                                                ?>
                                                <tr>
                                                    <td>
                                                        <input type="hidden" name="rowid[<?=$modulesVal['smuid']?>]" value="<?=$modulesVal['id']?>">

                                                        <?php echo $modulesVal['modulelist']['module_name'];?>
                                                    </td>
                                                    <td>
                                                        <input type="checkbox"  <?php if($modulesVal['can_write']==1) { echo "checked=checked"; } ?> name="add[<?php echo $modulesVal['sysmid'];?>]">
                                                    </td>
                                                    <td>
                                                        <input type="checkbox"  <?php if($modulesVal['can_edit']==1) { echo "checked=checked"; } ?> name="edit[<?php echo $modulesVal['sysmid'];?>]">
                                                    </td>
                                                    <td>
                                                        <input type="checkbox"  <?php if($modulesVal['can_delete']==1) { echo "checked=checked"; } ?> name="delete[<?php echo $modulesVal['sysmid'];?>]">
                                                    </td>
                                                    <td>
                                                        <input type="checkbox"   <?php if($modulesVal['can_view']==1) { echo "checked=checked"; } ?> name="view[<?php echo $modulesVal['sysmid'];?>]">
                                                    </td>
                                                <tr>
                                                 <?php 
                                                }
                                                ?>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                                <button type="submit" class="btn btn-primary">Update</button>
                            </div>
                        </div>
                    </form> 
                </div>
            </div>
        </div>
    </div>
</div>
<script>
$(document).ready(function() {
    $("#loader").fadeOut("slow");
});
</script>
@endsection

resources/views/role/index.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <div class="row">
        <div class="col-md-12 col-md-offset-0">
            <div class="panel panel-default">
                <div class="panel-heading"> Role Management</div>

                <div class="panel-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    @if ($message = Session::get('success'))
                    <div class="alert alert-success">
                        <p>{{ $message }}</p>
                    </div>
                    @endif
                                        
                    <div class="row">
                        <div class="col-lg-12 margin-tb">
                            <div class="pull-left">
                            
                            </div>
                            <?php if(\Auth::user()->user_role==2){?>
                            <div class="pull-right btn">
                                <a class="btn btn-success" href="{{ route('role.create') }}"> Assign Role</a>
                            </div>
                            <?php } ?>
                        </div>
                    </div>
                    <div class="table-responsive">
                    <table id="example" class="table table-striped table-bordered"  width="100%" >
                        <thead>
                            <tr>
                                <th>First Name</th>
                                <th>Last Name</th>
                                <th>Email</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php 
                            foreach($user as $v){?>
                            <tr>
                                <td><?=$v['name']?></td>
                                <td><?=$v['lastname']?></td>
                                <td><?=$v['email']?></td>
                                <td>
                                    <form onsubmit="return confirm('Do you really want to delete the roles?');" action="{{ route('roledelete',$v->id) }}" method="POST">
                                        <a class="btn btn-info" href="{{ route('role.show',$v->id) }}">View Role</a>
                                        <?php if(\Auth::user()->user_role==2){?>
                                            <a class="btn btn-primary" href="{{ route('role.edit',$v->id) }}">Edit Role</a>    
                                            {{ csrf_field() }}
                                            {{ method_field('DELETE') }}
                                        
                                            <button type="submit" class="btn btn-danger">Delete Role</button>
                                        <?php } ?>
                                    </form>
                                </td>
                            </tr>
                            <?php }?>
                        </tbody>
                        <tfoot>
                            <tr>
                                <th>First Name</th>
                                <th>Last Name</th>
                                <th>Email</th>
                                <th>Action</th>
                            </tr>
                        </tfoot>
                    </table>
                </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function() {
     $("#loader").fadeOut("slow");
     });
     </script>
@endsection

resources/views/role/load.blade.php
<div id="load" style="position: relative;">
    @foreach($country as $country1)
    <div>
        <h3>
            {{$country1->name }}</a>
        </h3>
    </div>
    @endforeach
</div>
{{ $country->links() }}

resources/views/role/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12 col-md-offset-0">
            <div class="panel panel-default">
                <div class="panel-heading"> View Role</div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-12 margin-tb">
                            <div class="pull-left">
                                
                            </div>
                            <div class="pull-right">
                                <a class="btn btn-primary" href="{{ route('role.index') }}"> Back</a>
                            </div>
                        </div>
                    </div>
					<div class="row">
						<div class="col-xs-12 col-sm-12 col-md-12">
							<div class="form-group">
								<strong>Name:</strong>
								{{ $user[0]['name'] }}  {{ $user[0]['lastname'] }}

							</div>
						</div>
						<div class="col-xs-12 col-sm-12 col-md-12">
							<div class="form-group">
								<strong>Email:</strong>
								{{ $user[0]['email'] }}
							</div>
						</div>
						<div class="col-xs-12 col-sm-12 col-md-12">
							<div class="table-responsive">
								<table class="table">
									<thead>
										<tr>
											<th scope="col">Module Name</th>
											<th scope="col">Add</th>
											<th scope="col">Edit</th>
											<th scope="col">Delete</th>
											<th scope="col">View</th>
										</tr>
									</thead>
									<tbody>
									<?php 
									foreach($modules as $modulesKey=>$modulesVal){
										?>
										<tr>
											<td>	
												<?php echo $modulesVal['modulelist']['module_name'];?>
											</td>	
											<td>
												<input type="checkbox" disabled <?php if($modulesVal['can_write']==1) { echo "checked=checked"; } ?> name="add[<?php echo $modulesVal['id'];?>]">
											</td>	
											<td>
												<input type="checkbox" disabled <?php if($modulesVal['can_edit']==1) { echo "checked=checked"; } ?> name="edit[<?php echo $modulesVal['id'];?>]">
											</td>	
											<td>
												<input type="checkbox" disabled <?php if($modulesVal['can_delete']==1) { echo "checked=checked"; } ?> name="delete[<?php echo $modulesVal['id'];?>]">
											</td>	
											<td>
												<input type="checkbox"  disabled <?php if($modulesVal['can_view']==1) { echo "checked=checked"; } ?> name="view[<?php echo $modulesVal['id'];?>]">
											</td>
										<tr>
										<?php 
										}
									?>
									</tbody>
								</table>
							</div>
						</div>
					</div>     
                </div>
			</div>
		</div>
	</div>
</div>
<script>
$(document).ready(function() {
    $("#loader").fadeOut("slow");
});
</script>
@endsection